{% set name = "pyqtree" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Pyqtree-{{ version }}.tar.gz
  sha256: 4f36d5160ddf170d7245e9c7102a45211b85003383dd552b6cd109e50cc3af81

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyqtree
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/karimbahgat/Pyqtree
  summary: A pure Python quad tree spatial index for GIS or rendering usage.
  doc_url: https://pythonhosted.org/Pyqtree/
  license: MIT
  # License file manually packaged. See https://github.com/karimbahgat/Pyqtree/pull/20
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joaquin
